import libs_enc = libbrotli%lib{brotlienc}
import libs_dec = libbrotli%lib{brotlidec}

./: exe{driver-enc driver-dec}

exe{driver-enc}: c{driver-enc} $libs_enc
exe{driver-dec}: c{driver-dec} $libs_dec
